### Get all contacts
GET http://localhost:8080/contacts



### Get one contact by ID
GET http://localhost:8080/contacts/690ad92a3a5db497de7202d3



### Create a new contact (POST)
POST http://localhost:8080/contacts
Content-Type: application/json

{
  "firstName": "Ricardo",
  "lastName": "Vargas",
  "email": "ricardo.vargas@example.com",
  "favoriteColor": "blue",
  "birthday": "1990-01-01"
}



### Update a contact (PUT)
PUT http://localhost:8080/contacts/690ad92a3a5db497de7202d3
Content-Type: application/json

{
  "firstName": "Ricardo",
  "lastName": "Vargas",
  "email": "ricardo.vargas@example.com",
  "favoriteColor": "green",
  "birthday": "1990-02-02"
}



### Delete a contact (DELETE)
DELETE http://localhost:8080/contacts/690ad92a3a5db497de7202d3